#port
server:
  port: 8090
  servlet:
    session:
      timeout: 30m


#server.tomcat.uri-encoding=utf-8

  #the config about database
spring:
  thymeleaf:
    prefix: classpath:/templates/
    encoding: UTF-8
    mode: HTML5
    suffix: .html
    cache: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flink_test
    username: root
    password: s374857303

mybatis:
  mapper-locations: classpath:mapper/*.xml





















